import React from 'react'
import { createRoot } from 'react-dom/client'
import { api } from './api'
import './styles.css'

const session = () => JSON.parse(localStorage.getItem('session') || 'null')
function Nav({ go, logout }) { return <nav><strong>RES NAM</strong><button onClick={()=>go('feed')}>Reports</button>{session()?<><button onClick={()=>go('new')}>New report</button><button onClick={logout}>Log out</button></>:<><button onClick={()=>go('login')}>Log in</button><button onClick={()=>go('register')}>Register</button></>}</nav> }
function Auth({register,done}) { const [form,setForm]=React.useState({}),[error,setError]=React.useState(''); const submit=async e=>{e.preventDefault();try{const d=register?await api.register(form):await api.login(form);localStorage.setItem('session',JSON.stringify(d));done()}catch(x){setError(x.message)}};return <section className="panel"><h1>{register?'Create account':'Log in'}</h1><form onSubmit={submit}>{register&&<input placeholder="Name" required onChange={e=>setForm({...form,name:e.target.value})}/>}<input type="email" placeholder="Email" required onChange={e=>setForm({...form,email:e.target.value})}/><input type="password" placeholder="Password" required onChange={e=>setForm({...form,password:e.target.value})}/><button className="primary">{register?'Register':'Log in'}</button></form>{error&&<p className="error">{error}</p>}</section> }
function Feed({go}) { const [reports,setReports]=React.useState([]);React.useEffect(()=>{api.reports().then(x=>setReports(x.reports||[]))},[]);return <section><h1>Community reports</h1>{reports.length?reports.map(r=><article key={r.id}><h2><button className="link" onClick={()=>go('detail',r.id)}>{r.title}</button></h2><p>{r.category} · severity {r.severity} · {r.status}</p><p>{r.description}</p></article>):<p>No reports yet.</p>}</section> }
function NewReport({done}) { const [form,setForm]=React.useState({severity:3}),[error,setError]=React.useState('');const submit=async e=>{e.preventDefault();try{await api.createReport({...form,severity:Number(form.severity),latitude:Number(form.latitude),longitude:Number(form.longitude)});done()}catch(x){setError(x.message)}};return <section className="panel"><h1>Submit report</h1><form onSubmit={submit}>{['title','category','description','latitude','longitude'].map(k=><input key={k} required={k!=='description'} placeholder={k} onChange={e=>setForm({...form,[k]:e.target.value})}/>)}<input type="number" min="1" max="5" value={form.severity} onChange={e=>setForm({...form,severity:e.target.value})}/><button className="primary">Submit</button></form>{error&&<p className="error">{error}</p>}</section> }
function Detail({id}) { const [report,setReport]=React.useState(null),[body,setBody]=React.useState('');const load=()=>api.report(id).then(setReport);React.useEffect(load,[id]);if(!report)return <p>Loading…</p>;return <section><h1>{report.title}</h1><p>{report.category} · severity {report.severity} · {report.status}</p><p>{report.description}</p><button onClick={()=>api.like(id).then(load)}>Like / unlike</button><h2>Comments</h2>{report.comments?.map(c=><p key={c.id}><b>{c.user?.name||'User'}:</b> {c.body}</p>)}{session()&&<form onSubmit={e=>{e.preventDefault();api.comment(id,{body}).then(()=>{setBody('');load()})}}><input value={body} required placeholder="Add a comment" onChange={e=>setBody(e.target.value)}/><button>Comment</button></form>}</section> }
function App(){const [view,setView]=React.useState('feed'),[id,setId]=React.useState();const go=(v,i)=>{setView(v);setId(i)};return <><Nav go={go} logout={()=>{localStorage.removeItem('session');go('feed')}}/><main>{view==='login'&&<Auth done={()=>go('feed')}/>} {view==='register'&&<Auth register done={()=>go('feed')}/>} {view==='new'&&<NewReport done={()=>go('feed')}/>} {view==='detail'&&<Detail id={id}/>} {view==='feed'&&<Feed go={go}/>}</main></>}
createRoot(document.getElementById('root')).render(<App />)
